version: "3"

services:

  postgres:
    image: timescale/timescaledb:latest-pg15
    ports:
      - 127.0.0.1:5432:5432 # only for development purposes
    environment:
      - POSTGRES_PASSWORD=${PG_PASS:?err}
      - AUTH_PASS=${AUTH_PASS:?err}
    volumes:
      - ./scripts/setup.sh:/docker-entrypoint-initdb.d/setup.sh
      - ./scripts/setup.sql:/setup.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s

  api:
    image: postgrest/postgrest:latest
    ports:
      - 3000:3000
    environment: # https://postgrest.org/en/stable/references/configuration.html#environment-variables
      - PGRST_DB_URI=postgres://authenticator:${AUTH_PASS:?err}@postgres:5432/postgres
      - PGRST_DB_ANON_ROLE=anon
    depends_on:
      postgres:
        condition: service_healthy

